name: Deploy Maven Package

on:
  workflow_run:
    workflows: ["Build and Test Maven Package"]
    types: [completed]

jobs:

  deploy-maven-package:

    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') }}
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKFLOW_REF: ${{ github.event.workflow_run.head_branch }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: maven-repo

    - name: Add GitHub Server Credentials to Maven settings.xml
      uses: s4u/maven-settings-action@v2.4.0

    - name: Prepare Version
      id: prep
      run: |
        echo ::set-output name=version::${WORKFLOW_REF#refs/tags/v}

    - name: Set Version in Maven Parent Project and Submodules
      run: mvn -q versions:set -DnewVersion="${{ steps.prep.outputs.version }}" -DprocessAllModules=true

    - name: Build and Deploy Maven Packages
      run: mvn -q deploy
