name: Build and Test Maven Package

on:
  push:
    branches:
    - main
    - automated-maven-build
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: maven-repo

    - name: Start FHIR test server
      run: docker-compose -f docker-compose-test.yml up -d

    - name: Wait for FHIR Server Running
      uses: ifaxity/wait-on-action@v1
      with:
        resource: http-get://localhost:8080/fhir/CapabilityStatement
        timeout: 60000

    - name: Initialize FHIR test data
      run: bash ./init-testdata.sh

    - name: Build
      run: mvn -B package
